# Generated by Django 5.1.7 on 2026-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adminprofile_driverdocument_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='True si le numéro de téléphone a été vérifié par OTP.'),
        ),
    ]
