# Generated by Django 5.1.7 on 2026-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_phone_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('service_tier', models.CharField(choices=[('economy', 'Economy'), ('confort', 'Confort'), ('confort_plus', 'Confort +')], db_index=True, max_length=20, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='Prix de prise en charge, appliqué quelle que soit la distance.', max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, help_text='Prix minimum facturé, même pour une très courte distance.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Distance à vol d'oiseau entre départ et destination, calculée à la création.", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requested_service_tier',
            field=models.CharField(choices=[('economy', 'Economy'), ('confort', 'Confort'), ('confort_plus', 'Confort +')], db_index=True, default='economy', max_length=20),
        ),
    ]
