# Generated by Django 5.2.17 on 2026-08-31 14:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('airtel_money', 'Airtel Money'), ('moov_money', 'Moov Money'), ('bank_transfer', 'Bank transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_commission_settlements', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlements', to='core.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('driver_net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], db_index=True, default='pending', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='core.course')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='core.driver')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='core.commissionsettlement')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='commission_setting_rate_between_0_100')],
            },
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='commission_settlement_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='commission_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='commission_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(('driver_net_amount__gte', 0)), name='commission_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='commission_rate_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='commission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('settlement__isnull', True), ('status', 'pending')), models.Q(('settlement__isnull', False), ('status', 'paid')), _connector='OR'), name='paid_commission_requires_settlement'),
        ),
    ]
