# Generated by Django 5.2.17 on 2026-09-15 18:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_commissionsettlement_commission_commissionsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('closed', 'Closed')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='core.driver')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('released', 'Released')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reservation', to='core.course')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reservations', to='core.driver')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_reservations', to='core.driverwallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('provider', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('moov_money', 'Moov Money'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='core.driverwallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Top up'), ('commission', 'Commission'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=10)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='core.commission')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to='core.course')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.driverwallet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='driverwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='driverwallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__gte', 0)), name='wallet_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='driverwallet',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_balance__lte', models.F('balance'))), name='wallet_reserved_lte_balance'),
        ),
        migrations.AddConstraint(
            model_name='commissionreservation',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_amount__gt', 0)), name='commission_res_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettopup',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_topup_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettopup',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False), models.Q(('provider_reference', ''), _negated=True)), fields=('provider', 'provider_reference'), name='wallet_topup_provider_ref_unique'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_tx_wallet_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['type', 'created_at'], name='wallet_tx_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status', 'created_at'], name='wallet_tx_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_tx_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_before__gte', 0)), name='wallet_tx_before_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='wallet_tx_after_non_negative'),
        ),
    ]
