# Generated by Django 5.2.17 on 2026-09-16 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_driverwallet_commissionreservation_wallettopup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionreservation',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='commissionreservation',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commissionsettlement',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_settlement', to='core.wallettransaction'),
        ),
        migrations.AlterField(
            model_name='commissionsettlement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_commission_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionsettlement',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('airtel_money', 'Airtel Money'), ('moov_money', 'Moov Money'), ('bank_transfer', 'Bank transfer'), ('wallet', 'Wallet')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='commissionreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_rate__isnull', True), ('gross_amount__isnull', True)), models.Q(('commission_rate__isnull', False), ('gross_amount__isnull', False)), _connector='OR'), name='commission_res_snapshot_complete'),
        ),
        migrations.AddConstraint(
            model_name='commissionreservation',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__isnull', True), ('gross_amount__gte', 0), _connector='OR'), name='commission_res_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commissionreservation',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__isnull', True), models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), _connector='OR'), name='commission_res_rate_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='commissionsettlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('payment_mode', 'wallet'), _negated=True), ('confirmed_by__isnull', False), ('wallet_transaction__isnull', True)), models.Q(('confirmed_by__isnull', True), ('payment_mode', 'wallet'), ('wallet_transaction__isnull', False)), _connector='OR'), name='commission_settlement_source_consistent'),
        ),
    ]
