# Generated by Django 5.2.17 on 2026-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_commissionreservation_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettopup',
            name='initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettopup',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
