# Generated by Django 5.2.17 on 2026-09-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_wallettopup_initiated_at_wallettopup_provider_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_topup_id', models.PositiveBigIntegerField()),
                ('provider', models.CharField(choices=[('airtel_money', 'Airtel Money'), ('moov_money', 'Moov Money'), ('other', 'Other')], max_length=30)),
                ('provider_reference', models.CharField(max_length=120)),
                ('callback_status', models.CharField(max_length=20)),
                ('provider_status', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('processed', models.BooleanField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='core.wallettopup')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_events', to='core.wallettransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'provider_reference'], name='core_wallet_provide_0ee3dc_idx'), models.Index(fields=['reported_topup_id', 'created_at'], name='core_wallet_reporte_a4badc_idx'), models.Index(fields=['outcome', 'created_at'], name='core_wallet_outcome_81fe0a_idx')],
            },
        ),
    ]
