"""
Django settings for transport_platform project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

from datetime import timedelta
import os
from pathlib import Path

from dotenv import load_dotenv


# =========================================================
# BASE
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

DEBUG = (
    os.environ.get(
        'DJANGO_DEBUG',
        'False',
    )
    == 'True'
)

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS',
    'localhost,127.0.0.1',
).split(',')


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'drf_spectacular',
    'corsheaders',
    'channels',

    'core.apps.CoreConfig',
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'transport_platform.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [
    {
        'BACKEND':
            'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# =========================================================
# WSGI / ASGI
# =========================================================

WSGI_APPLICATION = (
    'transport_platform.wsgi.application'
)

ASGI_APPLICATION = (
    'transport_platform.asgi.application'
)


# =========================================================
# CHANNELS
# =========================================================
#
# Pour le développement local :
# mémoire interne.
#
# Plus tard en production :
# Redis pourra remplacer cette configuration.
# =========================================================

CHANNEL_LAYERS = {
    'default': {
        'BACKEND':
            'channels.layers.InMemoryChannelLayer',
    },
}


# =========================================================
# DATABASE
# =========================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(
            os.environ.get(
                'SQLITE_PATH',
                BASE_DIR / 'db.sqlite3',
            )
        ),
    }
}

# =========================================================
# REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    'DEFAULT_SCHEMA_CLASS':
        'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# =========================================================
# OPENAPI
# =========================================================

SPECTACULAR_SETTINGS = {
    'TITLE':
        'Djina API',

    'DESCRIPTION':
        'Documentation et test des endpoints (Courses, Payments, Drivers, etc.)',

    'VERSION':
        '1.0.0',

    'SERVE_INCLUDE_SCHEMA':
        False,

    'COMPONENT_SPLIT_REQUEST':
        True,

    'SECURITY': [
        {
            'bearerAuth': [],
        },
    ],

    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type':
                    'http',

                'scheme':
                    'bearer',

                'bearerFormat':
                    'JWT',
            },
        },
    },
}


# =========================================================
# JWT
# =========================================================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':
        timedelta(days=1),

    'REFRESH_TOKEN_LIFETIME':
        timedelta(days=7),

    'AUTH_HEADER_TYPES': (
        'Bearer',
    ),
}


# =========================================================
# USER
# =========================================================

AUTH_USER_MODEL = 'core.CustomUser'


# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get(
    'EMAIL_HOST_USER',
    '',
)

EMAIL_HOST_PASSWORD = os.environ.get(
    'EMAIL_HOST_PASSWORD',
    '',
)


ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_LOGIN_METHODS = {
    'email',
}

ACCOUNT_EMAIL_VERIFICATION = (
    'mandatory'
)

ACCOUNT_LOGOUT_ON_GET = True


# =========================================================
# FRONTEND
# =========================================================

FRONTEND_URL = (
    'http://localhost:3000'
)


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNATIONALISATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC
# =========================================================

STATIC_URL = 'static/'

STATIC_ROOT = (
    BASE_DIR / 'static'
)


DEFAULT_AUTO_FIELD = (
    'django.db.models.BigAutoField'
)


# =========================================================
# CORS
# =========================================================

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',

    'http://localhost:3001',
    'http://127.0.0.1:3001',

    'http://localhost:5173',
    'http://127.0.0.1:5173',

    'http://localhost:5174',
    'http://127.0.0.1:5174',
]


# =========================================================
# CACHE
# =========================================================

CACHES = {
    'default': {
        'BACKEND':
            'django.core.cache.backends.locmem.LocMemCache',
    },
}


# =========================================================
# SMS
# =========================================================

SMS_BACKEND = (
    'core.sms.TwilioSMSBackend'
)

SMS_FROM = os.environ.get(
    'SMS_FROM',
    '',
)

TWILIO_FROM_NUMBER = (
    os.environ.get(
        'TWILIO_FROM_NUMBER',
        '',
    )
)

TWILIO_ACCOUNT_SID = (
    os.environ.get(
        'TWILIO_ACCOUNT_SID',
        '',
    )
)

TWILIO_AUTH_TOKEN = (
    os.environ.get(
        'TWILIO_AUTH_TOKEN',
        '',
    )
)